# Carga de SQL

In [9]:
import pandas as pd
import sqlite3

df_produccion = pd.read_csv("../data/processed/produccion_limpia.csv")
df_deforestacion = pd.read_csv("../data/processed/deforestacion_limpia.csv")

df_produccion.head()

,cultivo,anio,campania,provincia,provincia_id,departamento,departamento_id,superficie_sembrada_ha,superficie_cosechada_ha,produccion_tm,rendimiento_kgxha
0,maíz,1969,1969/1970,Córdoba,14,Ischilín,14049,3500,1300,1500,1154
1,maíz,1969,1969/1970,Córdoba,14,General San Martín,14042,7500,6200,9300,1500
2,maíz,1969,1969/1970,Buenos Aires,6,Cañuelas,6134,4100,4000,10400,2600
3,maíz,1969,1969/1970,Buenos Aires,6,Campana,6126,2700,2650,7155,2700
4,maíz,1969,1969/1970,Buenos Aires,6,Brandsen,6119,3800,3700,9620,2600

## creamos la base de datos y cargamos las dos tablas

In [10]:
conexion = sqlite3.connect("../database/trazabilidad.db")

df_produccion.to_sql("produccion", conexion, if_exists="replace", index=False)
df_deforestacion.to_sql("deforestacion", conexion, if_exists="replace", index=False)

print("Tablas creadas correctamente")

Tablas creadas correctamente

In [11]:
query = """
SELECT *
FROM produccion
LIMIT 5;
"""

pd.read_sql(query, conexion)

,cultivo,anio,campania,provincia,provincia_id,departamento,departamento_id,superficie_sembrada_ha,superficie_cosechada_ha,produccion_tm,rendimiento_kgxha
0,maíz,1969,1969/1970,Córdoba,14,Ischilín,14049,3500,1300,1500,1154
1,maíz,1969,1969/1970,Córdoba,14,General San Martín,14042,7500,6200,9300,1500
2,maíz,1969,1969/1970,Buenos Aires,6,Cañuelas,6134,4100,4000,10400,2600
3,maíz,1969,1969/1970,Buenos Aires,6,Campana,6126,2700,2650,7155,2700
4,maíz,1969,1969/1970,Buenos Aires,6,Brandsen,6119,3800,3700,9620,2600

In [12]:
query = """
SELECT *
FROM deforestacion
LIMIT 5;
"""

pd.read_sql(query, conexion)

      provincia categoría_de_conservación  superficie_en_hectáreas
0  Buenos Aires                         I                      2.0
1  Buenos Aires                        II                    870.0
2  Buenos Aires                       III                    158.0
3  Buenos Aires             Sin categoría                      2.0
4     Catamarca                         I                    499.0